# Generated by Django 4.2.8 on 2023-12-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=155)),
                ('mark_score', models.IntegerField()),
                ('url', models.URLField(verbose_name='Url')),
            ],
        ),
    ]
